spring:
  data1:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/data1?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: mysql_lv
  data2:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/data2?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: mysql_lv

